### ISSUE TITLE
database error........usrname is null

### ISSUE THREAD

**Issue by pruthwirajs** [saveendhiman/XMPPSample_Studio#1]
I have difficulty in storing the message to sqlite data base.What is username in sqlite

[java.sql.SQLException: argument for 'username' is null
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.stmt.query.BaseComparison.appendArgOrValue(BaseComparison.java:66)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.stmt.query.BaseComparison.appendValue(BaseComparison.java:56)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.stmt.query.SimpleComparison.appendValue(SimpleComparison.java:12)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.stmt.query.BaseComparison.appendSql(BaseComparison.java:47)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.stmt.query.SimpleComparison.appendSql(SimpleComparison.java:12)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.stmt.Where.appendSql(Where.java:590)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.stmt.StatementBuilder.appendWhereStatement(StatementBuilder.java:158)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.stmt.QueryBuilder.appendWhereStatement(QueryBuilder.java:476)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.stmt.StatementBuilder.appendStatementString(StatementBuilder.java:140)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.stmt.StatementBuilder.buildStatementString(StatementBuilder.java:123)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.stmt.StatementBuilder.prepareStatement(StatementBuilder.java:74)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.stmt.QueryBuilder.prepare(QueryBuilder.java:106)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.stmt.QueryBuilder.query(QueryBuilder.java:361)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.stmt.Where.query(Where.java:503)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.dao.BaseDaoImpl.queryForEq(BaseDaoImpl.java:245)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.confidential.costbo.business.data.DatabaseHelper$1.call(DatabaseHelper.java:108)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.confidential.costbo.business.data.DatabaseHelper$1.call(DatabaseHelper.java:105)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:168)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:124)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.confidential.costbo.business.data.DatabaseHelper.updateContact(DatabaseHelper.java:104)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at com.confidential.costbo.business.Home.ActivityChatScreen$12$1.run(ActivityChatScreen.java:747)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at android.os.Handler.handleCallback(Handler.java:810)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at android.os.Looper.loop(Looper.java:189)
12-16 19:04:48.338 13028-13028/com.confidential.costbo.business W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5550)
12-16 19:04:48.339 13028-13028/com.confidential.costbo.business W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-16 19:04:48.339 13028-13028/com.confidential.costbo.business W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
12-16 19:04:48.339 13028-13028/com.confidential.costbo.business W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1015)
12-16 19:04:48.339 13028-13028/com.confidential.costbo.business W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
Is there any server side set up for getting notification.](url)

**Comment by saveendhiman** [comment]
hi
thanks for reporting this issue. Will look and fix this one. You can customize as your need.

Thanks 
Saveen

**Comment by pruthwirajs** [comment]
Thanks a lot for your help...Please give me some logic for how to implement group chat.

**Comment by saveendhiman** [comment]
Group chat you can do with the help of MUC. In openfire you can make custom plugin. All creation of groups, deletion and updation handle by custom plugin.
