### ISSUE TITLE
can't receive message from each other

### ISSUE THREAD

**Issue by hanxirui** [saveendhiman/XMPPSample_Studio#2]
I'm sorry for asking a silly question

**Comment by hanxirui** [comment]
Thank you so much for sharing
After I run, can see the login successful,
But you cannot receive messages sent by the other party
Would you please tell me whether to send a failure or receive a failure, or do I have a local configuration failure?
The running environment is MacOS, openfire, 4.1.4

![image](https://cloud.githubusercontent.com/assets/5877842/26713608/0bfc4640-47a0-11e7-9fa1-aec928b19d9e.png)


![image](https://cloud.githubusercontent.com/assets/5877842/26713353/d0dd500a-479e-11e7-8323-e9b60eab97e8.png)

**Comment by saveendhiman** [comment]
hey, did you resolve your problem ?
